src/Web/MVC/Controllers/BasketController.cs
namespace MVC.Controllers
{
    public class BasketController : Controller
    {
        private readonly IBasketService _basketService;

        public BasketController(IBasketService basketService)
        {
            _basketService = basketService ?? throw new ArgumentNullException(nameof(basketService));
        }

        public async Task<IActionResult> BasketIndex()
        {
            var subId = User.Claims.FirstOrDefault(x => x.Type == "sub")?.Value;
            var response = await _basketService.GetBasketAsync(subId);

            if (response == null || !response.IsSuccess)
            {
                var result  = await _basketService.CreateBasketAsync(subId);
                if (result == null || !result.IsSuccess)
                {
                    TempData["error"] = "Basket cannot create.";
                    return RedirectToAction("Error", "Home"); 
                }
                
            }

            var basket = JsonConvert.DeserializeObject<BasketDto>(Convert.ToString(response.Result));
            return View(basket);
        }


        public async Task<IActionResult> AddProductIntoBasket(int productId, int quantity)
        {
            var subId = User.Claims.FirstOrDefault(x => x.Type == "sub")?.Value;
            if (subId == null)
            {
                TempData["error"] = "User not authenticated.";
                return RedirectToAction("Error", "Home"); 
            }

            var result = await _basketService.AddProductIntoBasketAsync(subId, productId, quantity);
            if (!result.IsSuccess)
            {
                TempData["error"] = result.Message;
                return RedirectToAction("Error", "Home"); 
            }

            return RedirectToAction("BasketIndex");
        }


        public async Task<IActionResult> RemoveProductFromBasket(int productId, int quantity)
        {
            var subId = User.Claims.FirstOrDefault(x => x.Type == "sub")?.Value;
            if (subId == null)
            {
                TempData["error"] = "User not authenticated.";
                return RedirectToAction("Error", "Home"); 
            }

            var result = await _basketService.DeleteProductFromBasketAsync(subId, productId, quantity);
            if (!result.IsSuccess)
            {
                TempData["error"] = result.Message;
                return RedirectToAction("Error", "Home"); 
            }

            return RedirectToAction("BasketIndex");
        }
        
        public async Task<IActionResult> Delete()
        {
            var subId = User.Claims.FirstOrDefault(x => x.Type == "sub")?.Value;
            var response = await _basketService.DeleteBasketAsync(subId);
        
            if (!response.IsSuccess)
            {
                TempData["error"] = response.Message; 
                return RedirectToAction("OrderIndex", "Order"); 
            }
        
            return RedirectToAction("BasketIndex");
        }
    }
}

src/Web/MVC/Controllers/ProductController.cs
namespace MVC.Controllers;

public class ProductController : Controller
    {
        private readonly IProductService _productService;
        private readonly IMapper _mapper;
        public ProductController(IProductService productService, IMapper mapper)
        {
             _productService = productService;
             _mapper = mapper;
        }

        public async Task<IActionResult> Index()
        {
            var response = await _productService.GetAllProductsAsync();
            if (!response.IsSuccess)
            {
                TempData["error"] = response.Message;
                return RedirectToAction("Error", "Home");
            }

            return View(JsonConvert.DeserializeObject<List<ProductDto>>(Convert.ToString(response.Result)));
        }

        public IActionResult Create()
        {

            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(ProductRequest addProductRequest)
        {
            if (!ModelState.IsValid)
            {
                return View("Error");
            }
            var product = _mapper.Map<ProductDto>(addProductRequest);
            var response = await _productService.CreateProductsAsync(product);
            if (!response.IsSuccess)
            {
                TempData["error"] = response.Message;
                return RedirectToAction("Error", "Home");
            }
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> Edit(int Id)
        {
            var response = await _productService.GetProductByIdAsync(Id);
            if (!response.IsSuccess)
            {
                TempData["error"] = response.Message;
                return RedirectToAction("Error", "Home");
            }
            var product = JsonConvert.DeserializeObject<ProductDto>(Convert.ToString(response.Result));

            if (product == null)
            {
                return RedirectToAction("Edit");
            }

            var viewProduct = _mapper.Map<ProductRequest>(product);
            return View(viewProduct);
        }
        
        [HttpPost]
        public async Task<IActionResult> Edit(ProductRequest updateProductRequest)
        {
            
            var product = _mapper.Map<ProductDto>(updateProductRequest);
            var response = await _productService.UpdateProductsAsync(product);
            if (!response.IsSuccess)
            {
                TempData["error"] = response.Message;
                return RedirectToAction("Error", "Home"); 
            }
            return RedirectToAction("Index");

        }

        public async Task<IActionResult> Delete(int id)
        {
            var response = await _productService.DeleteProductsAsync(id);
            if (!response.IsSuccess)
            {
                TempData["error"] = response.Message;
                return RedirectToAction("Error", "Home"); 
            }
            return RedirectToAction("Index");
        }
    }

src/Web/MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - eShop</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="//cdn.datatables.net/1.13.4/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.css"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.4/font/bootstrap-icons.css">
</head>
<style>
        .navbar {
          background-color: #414852 !important; 
        }
        
        

        .navbar-nav .nav-link {
          color: #b79191 !important;
        }
        
        body {
          background-color: #8da6b9 !important;
        }
    </style>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark  box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">eShop</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Order" asp-action="OrderIndex">
                               Manage Order
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Basket" asp-action="BasketIndex">
                             Basket
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Product" asp-action="Index">
                                   Product
                            </a>
                        </li>
                    </ul>
                    <ul class="navbar-nav">
                        @if (!User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link " asp-controller="Account" asp-action="Login">Login</a>
                            </li>
                        }
                        else
                        {
                            var userName = User.Claims.FirstOrDefault(x => x.Type == "name")?.Value;
                            <li class="nav-item">
                                <a class="nav-link" href="#">Hello @userName</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Account" asp-action="Logout">Logout</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
            <partial name="_Notifications" />
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="//cdn.datatables.net/1.13.4/js/jquery.dataTables.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

src/Web/MVC/Views/Shared/_Notifications.cshtml
@if(TempData["error"]!=null){
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.js" integrity="sha512-lbwH47l/tPXJYG9AcFNoJaTMhGvYWhVM9YI43CT+uteTRRaiLCui8snIgyAN8XWgNjNhCqlAUdzZptso6OCoFQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script type="text/javascript">
        toastr.error('@TempData["error"]')
        </script>
}
@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.js" integrity="sha512-lbwH47l/tPXJYG9AcFNoJaTMhGvYWhVM9YI43CT+uteTRRaiLCui8snIgyAN8XWgNjNhCqlAUdzZptso6OCoFQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]')
    </script>
}